### PR TITLE
Update pr.yml with peaceiris

### PR DESCRIPTION
**Pull request by tsridja**
add peaceiris

### CODE REVIEW

**Comment by tsridja** [comment]
add peaceiris back

**Review by ellielavenderscott — CHANGES_REQUESTED** [review]
action not working, please update to most recent version, fix publish dir to .public, and set the github token

**Comment by tsridja** [comment]
modified to v4

**Comment by ellielavenderscott** [comment]
Had to update repo settings to allow actions to write/read and commit

**Review by ellielavenderscott — APPROVED** [review]
thanks

**Pull request merged**
