### PR TITLE
AB#2201 Pyspelling

### PR DESCRIPTION
**Pull request by JMisenheimer**
Added Pyspelling to the pr.yml file

### CODE REVIEW

**Comment by ellielavenderscott** [comment]
Remove the checkout line #69

Also         uses: sbates130272/spellcheck-github-actions@v0.6.0ooo
typo with the 'ooo'? should be         uses: sbates130272/spellcheck-github-actions@v0.6.0

**Comment by JMisenheimer** [comment]
Ok. I will make corrections.

**Comment by JMisenheimer** [comment]
I've replaced the invalid field with continue-on-error: true

**Review by ellielavenderscott — CHANGES_REQUESTED** [review]
This looks almost correct but is still not working. 
It looks like you are missing the .spellcheck.yaml file with the config in the root directory. 

I found this: https://facelessuser.github.io/pyspelling/configuration/

Seems you will need to set this first. Let me know if you need help

**Comment by ellielavenderscott** [comment]
Thanks, it worked!

**Pull request merged**
